name: kpasslib
description: A Dart library for reading, modifying and writing KeePass v2 databases (KDBX version 3 or 4).
version: 1.0.8
repository: https://github.com/korovan-software/kpasslib

environment:
  sdk: '>=3.6.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.12

dependencies:
  archive: ^4.0.1
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.6
  cryptography: ^2.7.0
  hashlib: ^1.21.1
  pointycastle: ^3.9.0
  xml: ^6.2.2
